# Generated by Django 6.0.6 on 2026-07-02 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0002_clases_curso'),
        ('cursos', '0001_initial'),
        ('user', '0005_remove_usuario_clase_remove_usuario_curso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(max_length=10, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clase', to='clases.clases')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='cursos.cursos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='user.roles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
