# Generated by Django 6.0.6 on 2026-07-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=models.IntegerField(verbose_name='telefono'),
        ),
    ]
