# Generated by Django 6.1 on 2026-09-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, 'Período 1'), (2, 'Período 2'), (3, 'Período 3'), (4, 'Período 4')], verbose_name='Período')),
                ('anio', models.PositiveIntegerField(verbose_name='Año académico')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-anio', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('anio', 'numero'), name='periodo_unico_por_anio')],
            },
        ),
    ]
