# Generated by Django 6.1 on 2026-09-08 14:22

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha_inicio',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.localdate, message='La fecha de inicio no puede ser anterior a hoy.')], verbose_name='Fecha de inicio'),
        ),
    ]
