# Generated by Django 6.1.1 on 2026-09-15 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_alter_clases_options_alter_clases_curso_and_more'),
        ('cursos', '0001_initial'),
        ('docentes', '0004_remove_docente_clase_remove_docente_curso'),
        ('horario', '0003_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='activo',
        ),
        migrations.AddField(
            model_name='horario',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='clases.clases'),
        ),
        migrations.AddField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(default=12234, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='cursos.cursos'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('periodo', 'docente', 'dia', 'hora_inicio', 'hora_fin'), name='unique_horario_docente'),
        ),
    ]
