# Generated by Django 6.1 on 2026-08-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('academico', 'Académico'), ('reunion', 'Reunión'), ('evaluacion', 'Evaluación'), ('actividad', 'Actividad'), ('aviso', 'Aviso')], default='general', max_length=30)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('video', models.URLField(blank=True, null=True)),
                ('publico', models.CharField(choices=[('todos', 'Todos'), ('alumnos', 'Alumnos'), ('docentes', 'Docentes')], default='todos', max_length=20)),
                ('publicado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
