# Generated by Django 6.0.7 on 2026-07-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_verificacioncorreo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificacionCorreo',
        ),
    ]
