# Generated by Django 6.0.6 on 2026-07-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tareas_clase_tareas_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaalumno',
            name='calificada',
            field=models.BooleanField(default=False),
        ),
    ]
