# Generated by Django 6.1 on 2026-08-10 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_alter_docente_telefono'),
        ('tareas', '0003_respuestaalumno_calificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docentes.docente'),
        ),
    ]
