# Generated by Django 6.1 on 2026-08-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tareas_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='docente',
        ),
    ]
