# Generated by Django 6.1 on 2026-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_remove_tareas_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
