# Generated by Django 6.1 on 2026-08-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_asignaciondocente'),
        ('tareas', '0007_tareaalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='docente',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tareas',
                to='docentes.docente'
            ),
),
    ]