# Generated by Django 6.1 on 2026-08-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_tareas_docente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareas',
            options={},
        ),
    ]
