# Generated by Django 6.1.1 on 2026-09-16 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_alter_clases_options_alter_clases_curso_and_more'),
        ('cursos', '0001_initial'),
        ('docentes', '0004_remove_docente_clase_remove_docente_curso'),
        ('tareas', '0009_alter_tareas_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(default='Actividad', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Actividad de calificación',
                'verbose_name_plural': 'Actividades de calificación',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'Calificación de actividad',
                'verbose_name_plural': 'Calificaciones de actividades',
            },
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.UniqueConstraint(fields=('alumno', 'tarea'), name='unique_calificacion_alumno_tarea'),
        ),
        migrations.AddField(
            model_name='actividadcalificacion',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_calificacion', to='clases.clases'),
        ),
        migrations.AddField(
            model_name='actividadcalificacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_calificacion', to='cursos.cursos'),
        ),
        migrations.AddField(
            model_name='actividadcalificacion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_calificacion', to='docentes.docente'),
        ),
        migrations.AddField(
            model_name='calificacionactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='tareas.actividadcalificacion'),
        ),
        migrations.AddField(
            model_name='calificacionactividad',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_actividades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='calificacionactividad',
            constraint=models.UniqueConstraint(fields=('actividad', 'alumno'), name='unique_calificacion_actividad_alumno'),
        ),
    ]
