# Generated by Django 6.0.5 on 2026-09-21 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0004_remove_horario_activo_horario_clase_horario_curso_and_more'),
        ('tareas', '0010_actividadcalificacion_calificacionactividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='horario.periodo'),
        ),
    ]
