# Generated by Codex on 2026-09-21

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("horario", "0004_remove_horario_activo_horario_clase_horario_curso_and_more"),
        ("tareas", "0011_tareas_periodo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividadcalificacion",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="actividadcalificacion",
            name="clase",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="actividades_calificacion", to="clases.clases"),
        ),
        migrations.AddField(
            model_name="actividadcalificacion",
            name="periodo",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actividades_calificacion", to="horario.periodo"),
        ),
    ]
