# Generated by Django 6.1.1 on 2026-09-15 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_clases_curso'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clases',
            options={'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterField(
            model_name='clases',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='cursos.cursos'),
        ),
        migrations.AlterField(
            model_name='clases',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
