# Generated by Django 6.0.6 on 2026-07-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='telefono'),
        ),
    ]
