# Generated by Django 6.1 on 2026-08-28 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_clases_curso'),
        ('docentes', '0002_alter_docente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.clases')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='docentes.docente')),
            ],
            options={
                'verbose_name': 'Asignación de docente',
                'verbose_name_plural': 'Asignaciones de docentes',
                'unique_together': {('docente', 'clase')},
            },
        ),
    ]
