# Generated by Django 6.1.1 on 2026-09-17 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_alter_clases_options_alter_clases_curso_and_more'),
        ('docentes', '0006_alter_asignaciondocente_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignaciondocente',
            options={'verbose_name': 'Asignación de docente', 'verbose_name_plural': 'Asignaciones de docentes'},
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docentes', to='clases.clases'),
        ),
    ]
