# Generated by Django 6.0.6 on 2026-07-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumnos_curso'),
        ('clases', '0002_clases_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.clases'),
        ),
    ]
