# Generated by Django 6.1 on 2026-08-26 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumnos_clase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='nombre_acudiente',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='parentesco_acudiente',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='telefono_acudiente',
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acudiente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcudienteAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(default='Acudiente', max_length=50)),
                ('es_principal', models.BooleanField(default=True)),
                ('autorizado', models.BooleanField(default=True)),
                ('fecha_vinculacion', models.DateTimeField(auto_now_add=True)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_alumnos', to='alumnos.acudiente')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_acudientes', to='alumnos.alumnos')),
            ],
            options={
                'verbose_name': 'Relación acudiente-alumno',
                'verbose_name_plural': 'Relaciones acudiente-alumno',
                'constraints': [models.UniqueConstraint(fields=('acudiente', 'alumno'), name='unique_acudiente_alumno')],
            },
        ),
    ]
