# Generated by Django 6.1.1 on 2026-09-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_remove_alumnos_nombre_acudiente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='codigo',
        ),
    ]
